# Generated by Django 2.1.3 on 2018-11-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', models.CharField(max_length=255)),
                ('pulished', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=255)),
                ('used', models.IntegerField()),
            ],
            options={
                'db_table': 'girl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('img', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField()),
                ('is_delete', models.IntegerField()),
                ('is_vip', models.IntegerField()),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TFilm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.CharField(max_length=255)),
                ('actor', models.CharField(blank=True, max_length=255, null=True)),
                ('cata_log_name', models.CharField(max_length=255)),
                ('cata_log_id', models.CharField(blank=True, max_length=255, null=True)),
                ('evaluation', models.FloatField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('is_use', models.IntegerField()),
                ('loc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('loc_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('on_decade', models.CharField(blank=True, max_length=255, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_class_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_class_id', models.CharField(blank=True, max_length=255, null=True)),
                ('type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('update_time', models.CharField(blank=True, max_length=255, null=True)),
                ('is_vip', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_film',
                'managed': False,
            },
        ),
    ]
